"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import * as XLSX from "xlsx";
import * as THREE from "three";

type CellType = "floor" | "rack" | "wall" | "start" | "packing";
type Cell = { type: CellType; location?: string };
type OrderLine = { orderId: string; sku: string; quantity: number; location: string };
type Result = { batch: number; orderIds: string; units: number; picks: number; distance: number; seconds: number; resource: string };

const ROWS = 12, COLS = 18;
const key = (r:number,c:number) => `${r},${c}`;
const makeLayout = () => Array.from({length:ROWS},(_,r)=>Array.from({length:COLS},(_,c):Cell=> {
  if(r===10&&c===1) return {type:"start"};
  if(r===10&&c===16) return {type:"packing"};
  const rack = r>=2&&r<=8&&[3,4,7,8,11,12,15].includes(c);
  return rack ? {type:"rack", location:`R-${String(r*20+c).padStart(3,"0")}`} : {type:"floor"};
}));

function bfs(layout:Cell[][], from:[number,number], target:[number,number]) {
  const targets = layout[target[0]][target[1]].type === "rack"
    ? [[target[0]-1,target[1]],[target[0]+1,target[1]],[target[0],target[1]-1],[target[0],target[1]+1]].filter(([r,c])=>r>=0&&c>=0&&r<ROWS&&c<COLS&&layout[r][c].type!=="rack"&&layout[r][c].type!=="wall") as [number,number][]
    : [target];
  const q:[number,number][]=[from], prev=new Map<string,string|null>([[key(...from),null]]); let end:string|undefined;
  while(q.length){ const p=q.shift()!; if(targets.some(t=>t[0]===p[0]&&t[1]===p[1])){end=key(...p);break}
    for(const [dr,dc] of [[1,0],[-1,0],[0,1],[0,-1]]){const n:[number,number]=[p[0]+dr,p[1]+dc]; if(n[0]<0||n[1]<0||n[0]>=ROWS||n[1]>=COLS)continue; const cell=layout[n[0]][n[1]]; const k=key(...n); if(!prev.has(k)&&cell.type!=="rack"&&cell.type!=="wall"){prev.set(k,key(...p));q.push(n)}}}
  if(!end)return [from]; const out:[number,number][]=[]; for(let cur:string|null=end;cur;cur=prev.get(cur)??null){const [r,c]=cur.split(",").map(Number);out.push([r,c])} return out.reverse();
}

function Scene({layout, paths, mode}:{layout:Cell[][];paths:[number,number][][];mode:"cart"|"amr"}){
  const mount=useRef<HTMLDivElement>(null);
  useEffect(()=>{ if(!mount.current)return; const host=mount.current, scene=new THREE.Scene(); scene.background=new THREE.Color(0x07111f);
    const camera=new THREE.PerspectiveCamera(48,host.clientWidth/host.clientHeight,.1,1000); camera.position.set(16,19,23);camera.lookAt(COLS/2,0,ROWS/2);
    const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setSize(host.clientWidth,host.clientHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2));host.replaceChildren(renderer.domElement);
    scene.add(new THREE.HemisphereLight(0xb9e6ff,0x142030,2.2)); const dl=new THREE.DirectionalLight(0xffffff,2);dl.position.set(5,14,8);scene.add(dl);
    const floor=new THREE.Mesh(new THREE.BoxGeometry(COLS,.12,ROWS),new THREE.MeshStandardMaterial({color:0x172638,roughness:.85}));floor.position.set(COLS/2-.5,-.1,ROWS/2-.5);scene.add(floor);
    layout.forEach((row,r)=>row.forEach((cell,c)=>{if(cell.type==="floor")return; const colors:any={rack:0xf4b860,wall:0x526279,start:0x38d996,packing:0x9b87f5};const h=cell.type==="rack"?1.6:.35;const mesh=new THREE.Mesh(new THREE.BoxGeometry(.82,h,.82),new THREE.MeshStandardMaterial({color:colors[cell.type],roughness:.55}));mesh.position.set(c,h/2,r);scene.add(mesh)}));
    const agents=paths.map((_,i)=>{const g=new THREE.Group();const body=new THREE.Mesh(new THREE.CapsuleGeometry(.22,.5,4,8),new THREE.MeshStandardMaterial({color:mode==="cart"?0x46c7ff:0xff6b75}));body.position.y=.48;g.add(body);if(mode==="amr"){const amr=new THREE.Mesh(new THREE.BoxGeometry(.62,.22,.75),new THREE.MeshStandardMaterial({color:0x4cd6a8}));amr.position.set(.5,.16,0);g.add(amr)}scene.add(g);return g});
    let raf=0,start=performance.now(); const animate=(now:number)=>{paths.forEach((path,i)=>{if(!path.length||!agents[i])return;const progress=Math.max(0,(now-start)/650+i*.35);const whole=Math.floor(progress);const idx=whole%path.length,nxt=(idx+1)%path.length,f=progress-whole;const current=path[idx],next=path[nxt]??current;if(!current||!next)return;agents[i].position.set(THREE.MathUtils.lerp(current[1],next[1],f),0,THREE.MathUtils.lerp(current[0],next[0],f))});renderer.render(scene,camera);raf=requestAnimationFrame(animate)};raf=requestAnimationFrame(animate);
    const resize=()=>{camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight)};addEventListener("resize",resize);return()=>{cancelAnimationFrame(raf);removeEventListener("resize",resize);renderer.dispose()}
  },[layout,paths,mode]); return <div className="scene" ref={mount}/>;
}

function Simulator(){
  const [layout,setLayout]=useState<Cell[][]>(makeLayout); const [tool,setTool]=useState<CellType>("rack"); const [orders,setOrders]=useState<OrderLine[]>([]); const [mode,setMode]=useState<"cart"|"amr">("cart");
  const [workers,setWorkers]=useState(3),[resources,setResources]=useState(3),[capacity,setCapacity]=useState(24); const [running,setRunning]=useState(false),[paths,setPaths]=useState<[number,number][][]>([]),[results,setResults]=useState<Result[]>([]); const [speed,setSpeed]=useState(1);
  const locations=useMemo(()=>new Map(layout.flatMap((row,r)=>row.map((c,col)=>c.type==="rack"&&c.location?[c.location,[r,col] as [number,number]]:null).filter(Boolean) as [string,[number,number]][])),[layout]);
  const invalid=orders.filter(o=>!locations.has(o.location)); const totalUnits=orders.reduce((a,o)=>a+o.quantity,0);
  const paint=(r:number,c:number)=>setLayout(old=>old.map((row,rr)=>row.map((cell,cc)=>rr===r&&cc===c?{type:tool,...(tool==="rack"?{location:cell.location||`R-${String(r*20+c).padStart(3,"0")}`}:{})}:cell)));
  const loadExcel=async(file:File)=>{const wb=XLSX.read(await file.arrayBuffer());const rows=XLSX.utils.sheet_to_json<Record<string,unknown>>(wb.Sheets[wb.SheetNames[0]]);setOrders(rows.map(x=>({orderId:String(x.Order_ID??""),sku:String(x.SKU??""),quantity:Number(x.Quantity??0),location:String(x.Location??"")})).filter(x=>x.orderId&&x.sku&&x.quantity>0&&x.location));};
  const run=()=>{if(!orders.length||invalid.length)return; setRunning(true); const start=layout.flatMap((row,r)=>row.map((c,col)=>c.type==="start"?[r,col] as [number,number]:null)).find(Boolean) || [0,0] as [number,number];const pack=layout.flatMap((row,r)=>row.map((c,col)=>c.type==="packing"?[r,col] as [number,number]:null)).find(Boolean)||start;
    const byOrder=new Map<string,OrderLine[]>();orders.forEach(o=>byOrder.set(o.orderId,[...(byOrder.get(o.orderId)||[]),o]));const batches:OrderLine[][]=[];let cur:OrderLine[]=[];let load=0;for(const lines of byOrder.values()){const units=lines.reduce((a,b)=>a+b.quantity,0);if(cur.length&&load+units>capacity){batches.push(cur);cur=[];load=0}cur.push(...lines);load+=units}if(cur.length)batches.push(cur);
    const agentPaths:Array<[number,number][]> = Array.from({length:Math.min(resources,batches.length)},()=>[]);const out:Result[]=[];batches.forEach((batch,i)=>{let pos=start as [number,number], full:[number,number][]= [pos];const unique=[...new Set(batch.map(x=>x.location))];for(const loc of unique){const p=bfs(layout,pos,locations.get(loc)!);full.push(...p.slice(1));pos=p[p.length-1]}const back=bfs(layout,pos,pack as [number,number]);full.push(...back.slice(1));agentPaths[i%agentPaths.length].push(...full);const distance=Math.max(0,full.length-1);const pickSeconds=batch.reduce((a,b)=>a+b.quantity*6,0);const travel=distance/(mode==="cart"?1.15:1.65);const coordination=mode==="amr"?unique.length*4:0;out.push({batch:i+1,orderIds:[...new Set(batch.map(x=>x.orderId))].join(", "),units:batch.reduce((a,b)=>a+b.quantity,0),picks:unique.length,distance,seconds:Math.round((travel+pickSeconds+coordination)/speed),resource:`${mode==="cart"?"CART":"AMR"}-${(i%resources)+1}`})});setPaths(agentPaths);setResults(out);setTimeout(()=>setRunning(false),700);};
  const save=(kind:"json"|"xlsx")=>{const summary={mode,workers,resources,capacity,totalOrders:new Set(orders.map(o=>o.orderId)).size,totalUnits,totalSeconds:Math.max(0,...results.map(r=>r.seconds)),results};let blob:Blob,name:string;if(kind==="json"){blob=new Blob([JSON.stringify({generatedAt:new Date().toISOString(),layout,orders,summary},null,2)],{type:"application/json"});name="picking_simulation_result.json"}else{const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(results),"Batch Results");XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet([summary]),"Summary");XLSX.writeFile(wb,"picking_simulation_result.xlsx");return}const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)};
  const saveLayout=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(layout,null,2)],{type:"application/json"}));a.download="warehouse_layout.json";a.click()};
  const makesample=()=>{const loc=[...locations.keys()].slice(0,8);const rows=Array.from({length:16},(_,i)=>({Order_ID:`ORD-${String(Math.floor(i/2)+1).padStart(4,"0")}`,SKU:`SKU-${String(i+1).padStart(4,"0")}`,Quantity:(i%3)+1,Location:loc[i%Math.max(1,loc.length)]||"R-043"}));const wb=XLSX.utils.book_new();const ws=XLSX.utils.json_to_sheet(rows);ws["!cols"]=[{wch:16},{wch:16},{wch:12},{wch:14}];XLSX.utils.book_append_sheet(wb,ws,"Orders");XLSX.writeFile(wb,"picking_order_template.xlsx")};
  const kpi={orders:new Set(orders.map(o=>o.orderId)).size,batches:results.length,distance:results.reduce((a,b)=>a+b.distance,0),seconds:results.length?Math.max(...results.map(r=>r.seconds)):0};
  return <div className="simulator-shell"><main><header><div><span className="eyebrow">FULFILLMENT LAB / SIMULATOR</span><h1>FlowPick <b>3D</b></h1></div><div className="status"><i className={orders.length&&!invalid.length?"ok":""}/>{orders.length?`${orders.length}개 피킹 라인 · 오류 ${invalid.length}건`:"오더 파일 대기 중"}</div></header>
    <div className="workspace"><aside className="panel left"><section><h2>01 운영 모드</h2><div className="seg"><button className={mode==="cart"?"active":""} onClick={()=>setMode("cart")}>카트 수작업</button><button className={mode==="amr"?"active":""} onClick={()=>setMode("amr")}>AMR 협업</button></div></section>
      <section><h2>02 운영 변수</h2><label>작업자 수 <strong>{workers}</strong><input type="range" min="1" max="20" value={workers} onChange={e=>setWorkers(+e.target.value)}/></label><label>{mode==="cart"?"카트":"AMR"} 수 <strong>{resources}</strong><input type="range" min="1" max="20" value={resources} onChange={e=>setResources(+e.target.value)}/></label><label>대당 적재량 <strong>{capacity}개</strong><input type="range" min="1" max="100" value={capacity} onChange={e=>setCapacity(+e.target.value)}/></label><label>시뮬레이션 속도 <strong>{speed}×</strong><input type="range" min="1" max="8" value={speed} onChange={e=>setSpeed(+e.target.value)}/></label></section>
      <section><h2>03 레이아웃 도구</h2><div className="tools">{(["floor","rack","wall","start","packing"] as CellType[]).map(t=><button key={t} className={tool===t?"active":""} onClick={()=>setTool(t)}><i className={t}/>{{floor:"통로",rack:"랙",wall:"벽",start:"출발",packing:"완료"}[t]}</button>)}</div><button className="ghost" onClick={saveLayout}>레이아웃 JSON 저장</button></section></aside>
      <section className="stage panel"><div className="stagehead"><div><span>{results.length?"LIVE DIGITAL TWIN":"LAYOUT EDITOR"}</span><h2>{results.length ? `${mode==="cart"?"카트":"AMR"} 배치 피킹 시뮬레이션` : "센터 레이아웃을 설계하세요"}</h2></div><div className="legend"><i className="rack"/>랙 <i className="start"/>출발 <i className="packing"/>완료</div></div>
        {results.length?<Scene layout={layout} paths={paths} mode={mode}/>:<div className="grid" style={{gridTemplateColumns:`repeat(${COLS},1fr)`}}>{layout.map((row,r)=>row.map((cell,c)=><button key={key(r,c)} className={`cell ${cell.type}`} title={cell.location||cell.type} onClick={()=>paint(r,c)}><span>{cell.type==="rack"?cell.location?.replace("R-",""):cell.type==="start"?"S":cell.type==="packing"?"P":""}</span></button>))}</div>}
        <div className="stagebar"><span>{results.length?"3D 이동 경로 재생 중":"셀을 클릭해 선택한 요소를 배치합니다"}</span><button className="run" disabled={running||!orders.length||!!invalid.length} onClick={run}>{running?"계산 중…":"▶ 시뮬레이션 시작"}</button></div></section>
      <aside className="panel right"><section><h2>04 오더 데이터</h2><button className="template" onClick={makesample}>↓ 엑셀 템플릿 받기</button><label className="upload"><input type="file" accept=".xlsx,.xls" onChange={e=>e.target.files?.[0]&&loadExcel(e.target.files[0])}/><b>엑셀 오더파일 업로드</b><span>Order_ID · SKU · Quantity · Location</span></label>{invalid.length>0&&<p className="error">레이아웃에 없는 로케이션 {invalid.length}건</p>}</section>
        <section><h2>SIMULATION KPI</h2><div className="kpis"><div><span>주문</span><b>{kpi.orders}</b><small>orders</small></div><div><span>배치</span><b>{kpi.batches}</b><small>batches</small></div><div><span>이동거리</span><b>{kpi.distance}</b><small>cells</small></div><div><span>완료시간</span><b>{kpi.seconds}</b><small>sec</small></div></div></section>
        <section><h2>결과 저장</h2><div className="save"><button disabled={!results.length} onClick={()=>save("json")}>JSON</button><button disabled={!results.length} onClick={()=>save("xlsx")}>EXCEL</button></div><p className="note">결과에는 운영 변수, 배치별 주문·수량·이동거리·완료시간이 포함됩니다.</p></section></aside></div>
    <footer><span>FLOWPICK ENGINE 1.0</span><span>격자 1칸 = 1 m · 피킹 1개 = 6 sec</span><span>{mode==="amr"?"AMR은 이동만 수행 · 작업자 도착 후 피킹":"작업자가 카트와 함께 이동"}</span></footer></main></div>
}

export default function Home(){
  return <div className="site">
    <header className="site-header"><a className="brand" href="#home"><span className="brand-mark"/>FlowPick</a><nav><a href="#home">홈</a><a href="#solutions">솔루션 소개</a><a href="#simulator">시뮬레이터</a><a href="#guide">활용 방법</a><a className="nav-cta" href="#contact">문의하기</a></nav></header>
    <section className="hero-site" id="home"><div className="hero-copy-site"><span className="site-kicker">WAREHOUSE INTELLIGENCE STUDIO</span><h1>물류를 감이 아닌<br/><em>흐름</em>으로 설계합니다.</h1><p>현장을 이해하는 컨설턴트와 데이터를 검증하는 시뮬레이션. FlowPick은 복잡한 물류센터 의사결정을 실행 가능한 운영안으로 바꿉니다.</p><div className="hero-actions"><a className="btn-site primary" href="#simulator">시뮬레이션 시작</a><a className="btn-site" href="#solutions">솔루션 살펴보기</a></div><div className="hero-facts"><div><b>48</b><span>센터 개선 프로젝트</span></div><div><b>9.4%</b><span>평균 생산성 향상</span></div><div><b>4주</b><span>평균 진단 기간</span></div></div></div>
      <div className="hero-lab"><div className="lab-top"><span>● LIVE FLOW MODEL</span><small>SCENARIO / 04</small></div><div className="warehouse-art"><div className="racks r1"/><div className="racks r2"/><div className="racks r3"/><div className="racks r4"/><div className="flow-line"/><i className="amr a1"/><i className="amr a2"/></div><div className="lab-bottom"><div><b>1,284</b><span>ORDERS / HOUR</span></div><div><b>−18.7%</b><span>TRAVEL DISTANCE</span></div><a href="#simulator">▶</a></div></div>
    </section>
    <div className="ticker-site"><span>FLOW ANALYSIS　✦　LAYOUT OPTIMIZATION　✦　PICKING SIMULATION　✦　OPERATION DESIGN　✦　FLOW ANALYSIS　✦　LAYOUT OPTIMIZATION</span></div>
    <section className="site-section" id="solutions"><div className="section-intro"><span>01 / WHAT WE SOLVE</span><h2>현장을 읽고, 숫자로 검증하고,<br/>움직이는 운영을 만듭니다.</h2></div><div className="solution-grid"><article><small>01</small><i className="shape diamond"/><h3>운영 진단</h3><p>작업 동선과 인력 배치, 병목 구간을 데이터와 현장 관찰로 함께 분석합니다.</p></article><article><small>02</small><i className="shape circle"/><h3>디지털 시뮬레이션</h3><p>투자 전에 레이아웃과 카트·AMR 운영 조건을 가상 환경에서 빠르게 비교합니다.</p></article><article><small>03</small><i className="shape line"/><h3>실행 설계</h3><p>KPI와 단계별 로드맵까지 연결해 보고서에 머물지 않는 변화를 설계합니다.</p></article></div></section>
    <section className="sim-section" id="simulator"><div className="sim-intro"><span>02 / INTERACTIVE LAB</span><h2>당신의 오더와 레이아웃으로<br/>운영안을 직접 검증하세요.</h2><p>엑셀 오더를 업로드하고 카트 또는 AMR 조건을 설정하면 배치 피킹 경로와 KPI를 3D로 비교할 수 있습니다.</p></div><div className="sim-frame"><Simulator/></div></section>
    <section className="guide-section" id="guide"><div className="guide-head"><span>03 / HOW TO USE</span><h2>데이터 네 칸이면<br/>시뮬레이션이 시작됩니다.</h2></div><div className="steps"><article><b>01</b><h3>레이아웃 설계</h3><p>통로, 랙, 출발지와 완료 지점을 격자에 배치합니다.</p></article><article><b>02</b><h3>오더 업로드</h3><p>Order_ID, SKU, Quantity, Location 열을 가진 엑셀을 올립니다.</p></article><article><b>03</b><h3>조건 설정</h3><p>작업자와 카트·AMR 수, 적재량을 조정합니다.</p></article><article><b>04</b><h3>결과 비교</h3><p>3D 이동과 배치별 KPI를 확인하고 JSON·Excel로 저장합니다.</p></article></div></section>
    <section className="proof-section"><div><span>04 / PROVEN IMPACT</span><h2>숫자로 말하는<br/>운영의 변화.</h2><p>같은 물동량도 레이아웃과 배치 방식에 따라 결과는 달라집니다. FlowPick은 모든 시나리오를 같은 기준으로 비교합니다.</p></div><div className="proof-metrics"><article><b>24%</b><span>피커 이동거리 절감</span></article><article><b>31%</b><span>병목 대기시간 감소</span></article><article><b>1.8×</b><span>시나리오 검토 속도</span></article><article><b>100%</b><span>브라우저 기반 실행</span></article></div></section>
    <footer className="site-footer" id="contact"><div><span>FLOWPICK LOGISTICS CONSULTING</span><h2>당신의 센터에는<br/>어떤 흐름이 필요할까요?</h2></div><div className="contact-box"><a href="mailto:hello@flowpick.co.kr">프로젝트 문의하기 →</a><p>hello@flowpick.co.kr<br/>Seoul, Korea</p></div><small>© 2026 FLOWPICK. ALL RIGHTS RESERVED.</small></footer>
  </div>
}
